name: NeatChests
version: 0.5.0-alpha
main: com.kartibrown.neatchests.NeatChestsPlugin

description: Smart chest sorting with protection plugin support.
api-version: '26.2'
website: https://github.com/kartibrown/NeatChests

author: kartibrown

softdepend:
  - WorldGuard
  - Residence
  - Towny
  - GriefPrevention
  - LandsClaimPlugin

permissions:
  neatchests.reload:
    description: Reload NeatChests.
    default: op

  neatchests.sort:
    description: Allow players to sort supported containers.
    default: true
